name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifactId: ${{ steps.artifact-upload-step.outputs.artifact-id }}
    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          npm ci
          npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: html
          path: |
            .next
            package.json
            package-lock.json
            next.config.mjs
          retention-days: 3
          include-hidden-files: true

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Webhook remote VPS
        run: |
          curl -v -H "Content-Type: application/json" -d '{"artifactId": ${{needs.build.outputs.artifactId}}}' https://docvaricose.ru/deploy
