name: CI
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifactUrl: ${{ steps.artifact-upload-step.outputs.artifact-url }}
    steps:
      - uses: actions/checkout@v4
      - name: Build project
        run: |
          npm ci
          npm run build
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        id: artifact-upload-step
        with:
          name: html
          path: |
            .next
            package.json
            package-lock.json
            next.config.mjs
          retention-days: 5
          include-hidden-files: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Webhook remote VPS
        run: echo "Artifact url from previous job is ${{needs.build.outputs.artifactUrl}}"
